artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_path: D:/Electricity-Consumption-Prediction/Dataset/Steel_industry_data.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5